SET IDENTITY_INSERT [dbo].[FAQs] ON
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (1, N'Is Atelier free to use?', N'Atelier is free to browse and register. Individual courses are available at different price points. All prices are displayed on the course catalogue.', 1, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (2, N'Can I access courses on my phone?', N'Yes, the Atelier platform is fully responsive and works on all modern mobile browser. Simply open your phone browser and visit the Atelier website', 2, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (3, N'What courses does Atelier offer?', N'Atelier currently offers courses across five creative disciplines namely Visual Arts, Digital Arts, Photography, Film & Video, Creative Writing. Browse the full catalogue regularly to see if new courses are introduced by the Atelier team.', 3, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (4, N'How do I get my completion certificate?', N'Complete all modules in a course and pass the final assessments with a score above the passing mark. Your certificate will automatically be generated and available for download from your dashboard.', 4, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (5, N'Can I retake a quiz if I fail?', N'Yes, you can retake each quiz up to 3 times. Your best score will be used for your certificate', 5, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (6, N'How do I enroll in a course?', N'Browse the course catalogue and click on any course that intetrests you and click the enroll button. If the course is paid, you will be directed to the payment page.
Once payment is confirmed, you will have immediate access to all course contents', 6, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (7, N'How many courses can I enroll in at once?', N'There is no limit to how many courses you can enroll in simultaneously', 7, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (8, N'How do I earn XP and badges?', N'Atelier features a rewards system where you earn XP Points and achievement badges as you learn. Visit your dashboard to see your current XP level and progress.', 8, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (9, N'Who creates courses on Atelier?', N'All courses on Atelier are created and managed by its administration team. Course content is carefully made and chosen to ensure quality and relevance to the disciplines covered on the platform', 9, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (10, N'What should I do if I forgot my password?', N'On the login page, click the Forgot Password link and enter your registered email address. You will receive a password reset token. Enter the token on the reset page to create a new password.', 10, 1)
INSERT INTO [dbo].[FAQs] ([FAQID], [Question], [Answer], [OrderIndex], [IsActive]) VALUES (11, N'How do I contact Atelier support?', N'You can reach the Atelier support team through the General Inquiry form on the Contact Page.', 11, 1)
SET IDENTITY_INSERT [dbo].[FAQs] OFF
