//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atelier
{
    public partial class UserProfile
    {
        /// <summary>
        /// pnlNotFound control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        /// <summary>
        /// pnlProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlProfile;

        /// <summary>
        /// imgAvatar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRole;

        /// <summary>
        /// litBio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBio;

        /// <summary>
        /// lblXP control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblXP;

        /// <summary>
        /// lblBadges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBadges;

        /// <summary>
        /// lblCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCourses;

        /// <summary>
        /// pnlNoBadges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoBadges;

        /// <summary>
        /// rptBadges control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBadges;

        /// <summary>
        /// pnlNoCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoCourses;

        /// <summary>
        /// rptCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCourses;
    }
}
